name: Deploy PHP App to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker buildx build \
          --platform linux/amd64 \
          --load \
          -t ${{ secrets.DOCKER_USERNAME }}/php-app:latest \
          ./crud-php-simple

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/php-app:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop php-app || true
            docker rm php-app || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/php-app:latest
            docker run -d -p 80:80 --name php-app \
              -e DB_HOST="${{ secrets.DB_HOST }}" \
              -e DB_USER="${{ secrets.DB_USER }}" \
              -e DB_PASS="${{ secrets.DB_PASS }}" \
              -e DB_NAME="${{ secrets.DB_NAME }}" \
              ${{ secrets.DOCKER_USERNAME }}/php-app:latest
